<a href="https://colab.research.google.com/github/istanranjith175b-commits/Exploring-datasets/blob/main/exp5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
import numpy as np
df=pd.read_csv('Liver Data.csv')
df.head(10)
df['indirect_bilirubin']=df['Total Bilirubin']-df['Direct Bilirubin']
df

,Age of the patient,Gender of the patient,Total Bilirubin,Direct Bilirubin,Alkphos Alkaline Phosphotase,Sgpt Alamine Aminotransferase,Sgot Aspartate Aminotransferase,Total Protiens,ALB Albumin,A/G Ratio Albumin and Globulin Ratio,Result,indirect_bilirubin
0,65.0,Female,0.7,0.1,187.0,16.0,18.0,6.8,3.3,0.90,1,0.6
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1,5.4
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1,3.2
3,58.0,Male,1.0,0.4,182.0,14.0,20.0,6.8,3.4,1.00,1,0.6
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1,1.9
...,...,...,...,...,...,...,...,...,...,...,...,...
30686,50.0,Male,2.2,1.0,610.0,17.0,28.0,7.3,2.6,0.55,1,1.2
30687,55.0,Male,2.9,1.3,482.0,22.0,34.0,7.0,2.4,0.50,1,1.6
30688,54.0,Male,6.8,3.0,542.0,116.0,66.0,6.4,3.1,0.90,1,3.8
30689,48.0,Female,1.9,1.0,231.0,16.0,55.0,4.3,1.6,0.60,1,0.9
30690,30.0,Male,3.1,1.6,253.0,80.0,406.0,6.8,3.9,1.30,1,1.5

In [28]:
indb=df['indirect_bilirubin']
indb[np.abs(indb)>1]

1        5.4
2        3.2
4        1.9
5        1.1
11       1.4
        ...
30678    1.3
30686    1.2
30687    1.6
30688    3.8
30690    1.5
Name: indirect_bilirubin, Length: 9958, dtype: float64